sudo: required
services:
        - docker

before_install:
        - docker build -t andreisimi/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run andreisimi/react-test npm test -- --coverage

after_success:
        - docker build -t andreisimi/multi-client ./client
        - docker build -t andreisimi/multi-nginx ./nginx
        - docker build -t andreisimi/multi-server ./server
        - docker build -t andreisimi/multi-worker ./worker
        # Log in to the docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push andreisimi/multi-client
        - docker push andreisimi/multi-nginx
        - docker push andreisimi/multi-server
        - docker push andreisimi/multi-worker

        # Take those images and push them to docker hub :')
